spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123
    url: jdbc:mysql:///wechat_diancan
mybatis:
  mapper-locations: mapper/**/**.xml
  type-aliases-package: com.kgc.wechatorder.sys.pojo com.kgc.wechatorder.wechat.pojo com.kgc.wechatorder.mall.pojo
server:
  port: 8080
